# Janito System Prompt Profiles (Jinja2)

Janito now uses Jinja2 TXT files for all system prompt profiles and agent instructions. This replaces the previous Jinja2 template system.

## Format
- All prompt profiles are written in Jinja2 TXT (`.txt.j2`) files.
- Profiles are modular, supporting reusable fragments for operational and communication profiles.

## Structure
Profiles now support two main sections:
- **Operational Styles:** How the agent approaches tasks and operations.
- **Communication Styles:** How the agent interacts and communicates with users.

Fragments for these sections are defined in:
- `operational_profile_*.txt.j2`
- `communication_profile_*.txt.j2`

Profiles are composed dynamically: the profile manager selects the operational and communication profile fragments based on the profile name (e.g., `technical-concise`).

## Inheritance & Dynamic Composition
- Only one base template is needed: `system_prompt_template_base.txt.j2`.
- The base template includes profile fragments dynamically using variables:

```jinja2
{% block operational_profiles %}
    {% include operational_profile_fragment %}
{% endblock %}

{% block communication_profiles %}
    {% include communication_profile_fragment %}
{% endblock %}
```

- The profile manager sets `operational_profile_fragment` and `communication_profile_fragment` to the correct fragment filenames (e.g., `operational_profile_technical.txt.j2`, `communication_profile_concise.txt.j2`).

## Location
Prompt profiles and fragments are stored in `janito/agent/templates/profiles/`.

## Available Profiles

Profiles are composed by combining a communication style and an operational style:

    <communication>-<operational>

For example: `concise-technical`, `friendly-minimal`, `formal-default`, etc.

### Communication Styles

| Name        | Description |
|-------------|-------------|
| **concise** ✂️ | Uses brief, direct, and actionable language.<br>Avoids unnecessary elaboration. |
| **formal** 🏛️ | Maintains a professional, neutral, and precise tone.<br>Avoids colloquialisms. |
| **friendly** 😊 | Uses approachable, positive, and encouraging language.<br>Offers help and suggestions. |
| **inquisitive** ❓ | Frequently asks clarifying questions.<br>Encourages user input and checks for understanding. |

### Operational Styles

| Name        | Description |
|-------------|-------------|
| **default** ⚖️ | Follows standard procedures, balances safety and efficiency.<br>Cites relevant files and lines in responses. |
| **exploratory** 🔬 | Encourages hypothesis-driven exploration.<br>Logs assumptions and documents findings. |
| **minimal** 🧹 | Performs only essential steps.<br>Avoids unnecessary checks or verbosity. |
| **technical** 🛠️ | Prioritizes validation and explicit error handling.<br>Maintains traceability and documents all actions.<br>Performs detailed technical workflow steps. |

---

_Update any custom prompt profiles to use the new dynamic fragment structure._

_See the profile fragments in `janito/agent/templates/profiles/` for reference._

---
_generated by janito.dev_
