# Tool: create_directory

**Description:**
Create a new directory at the specified path.

| Argument   | Type    | Description                                   |
|------------|---------|-----------------------------------------------|
| path       | str     | Path for the new directory                    |
| overwrite  | bool, optional | Overwrite if directory exists (default: False) |
| **Returns**| str     | Status message indicating the result          |

**Example usage:**
create_directory(path="output/results", overwrite=False)

---
_generated by janito.dev_