# Tool: get_file_outline (formerly outline_file)

**Description:**
Get an outline of a file's structure. For Python files, uses regex pattern matching for class and function definitions. May not capture all edge cases or non-standard code structures.

| Argument   | Type | Description |
|------------|------|-------------|
| file_path  | str  | Path to the file. |
| **Returns**| str  | Outline of the file's structure, or error message. |

**Example usage:**
outline_file(file_path="src/main.py")

---
_generated by janito.dev_