# Tool: remove_directory

**Description:**
Remove a directory. If recursive=False and directory not empty, raises error.

| Argument   | Type | Description |
|------------|------|-------------|
| directory  | str  | Path to the directory to remove. |
| recursive  | bool, optional | Remove recursively if True. Defaults to False. |
| backup     | bool, optional | If True, create a backup (.bak.zip) before removing. Defaults to False. |
| **Returns**| str  | Status message indicating result, or error message. |

**Example usage:**
remove_directory(directory="build/", recursive=True, backup=True)

---
_generated by janito.dev_