# Tool: retrieve_memory

**Description:**
Retrieve a value previously stored using a key. Use this tool to recall information remembered earlier in the session.

| Argument   | Type | Description |
|------------|------|-------------|
| key        | str  | The identifier for the value to retrieve. |
| **Returns**| str  | The stored value, or a warning message if not found. |

**Example usage:**
retrieve_memory(key="session_id")

---
_generated by janito.dev_