# search_outline Tool

Search for function, class, or header names in the outline of supported files (Python, Markdown). Faster than full-text search for code context queries. Supports substring and regex matching.

## Arguments
- `directories` (list[str]): Directories to search in.
- `pattern` (str): Substring or regex to match in outline items (function/class/header names).
- `file_types` (list[str], optional): File extensions to include (default: ['.py', '.md']).
- `regex` (bool, optional): If True, use regex matching; otherwise, substring. Defaults to False.
- `recursive` (bool, optional): Whether to search subdirectories. Defaults to True.

## Returns
- `str`: Newline-separated summary of matches: file, line, symbol/type, matched text. Returns "No matches found." if nothing matches.

## Example Usage

```
search_outline(
    directories=["src", "docs"],
    pattern="load",
    file_types=[".py"],
    regex=False,
    recursive=True
)
```

---
_generated by janito.dev_
