# 🧰 Tools Reference

Janito uses these tools automatically based on your prompt and context. This table is for transparency and to help you understand what the agent can do.

| 🛠️ Tool              | 📝 Description                                                  | 🗝️ Key Arguments                                                                                       | 🔁 Returns                                  | 🗒️ Notes                                                                                   |
|-----------------------|------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|------------------------------------------|-----------------------------------------------------------------------------------------|
| **create_file**       | Create a new file, or overwrite if specified.                   | `path` (str): file path<br>`content` (str): file content<br>`overwrite` (bool, optional)<br>`backup` (bool, optional) | Success or error message                  | If `overwrite=True`, updates file if it exists. Can create backup before overwriting.   |
| **create_directory**  | Create a new directory at the specified path.                    | `path` (str): directory path<br>`overwrite` (bool, optional)                                       | Success or error message                  | Fails if directory exists unless overwrite is True.                                      |
| **fetch_url**         | Fetch and extract text from a web page.                          | `url` (str): web page URL<br>`search_strings` (list of str, optional)                               | Extracted text or warning                 | Useful for research or referencing online resources.                                    |
| **run_bash_command**  | Run a bash command and capture output.                           | `command` (str): bash command<br>`timeout` (int, optional)<br>`require_confirmation` (bool, opt.)   | File paths and line counts for output     | Requires bash (e.g., WSL or Git Bash on Windows). Use with caution.                     |
| **find_files**        | Search for files matching a pattern.                             | `directories` (list)<br>`pattern` (str)<br>`recursive` (bool, optional)                            | List of matching file paths               | Respects .gitignore.                                                                  |
| **outline_file**  | Get outline of a file's structure (classes, functions, etc.).    | `file_path` (str)                                                                                   | Outline summary                           | Useful for code navigation and analysis.                                               |
| **get_lines**         | Read lines or full content from a file.                          | `file_path` (str)<br>`from_line` (int, optional)<br>`to_line` (int, optional)                      | File content                              | Specify line range or omit for full file.                                              |
| **move_file**         | Move a file to a new location.                                   | `src_path` (str)<br>`dest_path` (str)<br>`overwrite` (bool, optional)<br>`backup` (bool, optional) | Success or error message                  | Can create backup before moving.                                                       |
| **remove_file**       | Remove a file.                                                   | `file_path` (str)<br>`backup` (bool, optional)                                                     | Success or error message                  | Can create backup before removing.                                                     |
| **remove_directory**  | Remove a directory (optionally recursively).                     | `directory` (str)<br>`recursive` (bool, optional)<br>`backup` (bool, optional)                     | Success or error message                  | Use recursive for non-empty dirs.                                                      |
| **replace_text_in_file** | Replace exact text in a file.                                 | `file_path` (str)<br>`search_text` (str)<br>`replacement_text` (str)<br>`replace_all` (bool, opt.) | Success or warning message                | Can replace all or first occurrence.                                                   |
| **validate_file_syntax** | Validate a file for syntax issues (Python, JSON, YAML).         | `file_path` (str): file path to validate                                                            | Syntax status or error message            | Supports .py/.pyw (Python), .json (JSON), .yml/.yaml (YAML). Returns error details.     |
| **run_python_command**| Execute Python code in a subprocess and capture output.          | `code` (str)<br>`timeout` (int, optional)                                                          | Output or file paths for output           | Useful for automation and testing.                                                     |
| **search_files**      | Search for a text pattern in files.                              | `directories` (list)<br>`pattern` (str)<br>`recursive` (bool, optional)                            | Matching lines from files                 | Respects .gitignore.                                                                  |
| **ask_user**          | Request clarification or input from the user interactively.      | `question` (str)                                                                                   | User response as a string                 | Used when agent needs explicit user input.                                              |
| **memory**            | Store and retrieve values for later use.                         | `key` (str): identifier<br>`value` (str, optional): value to store                                 | Success message or stored value           | Used for session memory and recall.                                                    |

---

For more details, see the codebase or tool docstrings.
